### ISSUE TITLE
refgenie build does not include subassets in seek_keys

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#100]
`refgnie build` does not include the subassets under the `seek_keys` key. It still treats them as separate assets:

```
refgenie build -c genomes.yaml rCRSd/fasta --fasta rCRSd/rCRSd.fa.gz
cat genomes.yaml
```

```yaml
config_version: 0.3
genome_folder: /Users/mstolarczyk/Desktop/testing/test_genomes
genome_server: http://refgenomes.databio.org
genomes:
  rCRSd:
    asset_packages:
      fasta:
        default:
          asset_path: fasta/rCRSd.fa
          asset_description: Sequences in the FASTA format
      fai:
        default:
          asset_path: fasta/rCRSd.fa.fai
          asset_description: Indexed fasta file, produced with samtools faidx
      chrom_sizes:
        default:
          asset_path: fasta/rCRSd.chrom.sizes
          asset_description: Chromosome sizes file
    genome_checksum: 32a37a52a377d95bfd4b3d66763e1396a4480f34ab5c318a
```
