### ISSUE TITLE
add tags layer to the config

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#106]
from @nsheff 

add `tags` section under "asset_name": So its:
```yaml
fasta:
  default_tag: x
  asset_description: (whole asset)
  tags:
    x: ...
      tag_description: ...
    y: ...
```

this makes the `tag_description` and `asset_description` two separate things
