### ISSUE TITLE
add more detail to the required assets

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#143]
`required_assets` section should be a list of dicts, with the following fields:
```yaml
required_assets: [
            {
                "key": "genome", # identifier in the command list and to use on the command line
                "default_path": "txomefa",  # asset registry path
                "description": "fasta asset for transcriptome"
            },
            {
                "key": "txome",
                "default_path": "genomefa",
                "description": "fasta asset for genome"
            }
        ],
```
