### ISSUE TITLE
refgenie pull error: cannot find fasta:default digest

### ISSUE THREAD

**Issue by Dale12138** [databio/refgenie#171]
Hi,
I have encountered this weird error for every genome I tried to download. For example, with "refgenie pull -g mouse_chrM2x -a bowtie2_index", i would get "Could not find 'mouse_chrM2x/fasta:default' digest. Populating with server data". Has anyone seen this error before? I would appreciate it so much if anyone could drop me some hints on how to fix this!!
Plus, I installed refgenie under python/2.7.9 
Cheers,
Dale

**Comment by stolarczyk** [comment]
hi @Dale12138. This is not an error. It's just info that your assets inventory is missing `mouse_chrM2x/fasta:default` asset. Therefore refgenie could not verify `mouse_chrM2x/bowtie2_index`'s provenance (checksum match between `mouse_chrM2x/bowtie2_index` and its parent -- `mouse_chrM2x/fasta`)

The asset you were trying to pull should be there, check with: 

```
refgenie seek mouse_chrM2x/bowtie2_index"
```

**Comment by stolarczyk** [comment]
it this was the first asset you pulled for `mouse_chrM2x` genome, your config should look something like this:

```yaml
mouse_chrM2x:
    assets:
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            seek_keys:
              bowtie2_index: mouse_chrM2x
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            asset_parents: ['mouse_chrM2x/fasta:default']
        default_tag: default
      fasta:
        tags:
          default:
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            asset_children: ['mouse_chrM2x/bowtie2_index:default']
```
