### ISSUE TITLE
genome configuration file

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#6]
genome configuration files look like:

```
# Genome configuration

genome_folder: $GENOMES
genome_server: http://localhost

genomes:
  hg38:
    bowtie2: indexed_bowtie2
    hisat2: indexed_hisat2
    tss_annotation: TSS.bed.gz
    gtf: blah.gtf
  mm10:
    bowtie2: indexed_bowtie2
    blacklist: blacklist/mm10.bed
 
  rCRSd:
    bowtie2: indexed_bowtie2
    bowtie: indexed_bowtie
```

we define a new variable: $REFGENIE, that points to this yaml file.
