### ISSUE TITLE
build configuration file

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#7]
```
# Build configuration

tools:
  # absolute paths to required tools
  bowtie2build: bowtie2-build
  bismark_genome_preparation: bismark_genome_preparation
  epilog_indexer: epilog_indexer.py
  samtools: samtools
  kallisto: kallisto
  hisat2build: hisat2-build

index:
  bowtie2: True
  bismark_bt1: False
  bismark_bt2: False
  epilog: False
  hisat: False
  kallisto: True

param:
  epilog:
    context: "cg"
```

need to rename to 'build configuration' to distinguish from 'genome configuration'
