### ISSUE TITLE
no way to remove just one subasset

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#90]
related to https://github.com/databio/refgenie/issues/71

there's no way to remove `fai` asset from the config, since the removal of `fasta` deleted the `fasta` directory. The `fai` entry still exists in the config and is listed by `refgenie list`

```
[mstolarczyk@MichalsMBP test_genomes]: refgenie remove -g rCRSd -a fasta
refgenie 0.6.0
Remove rCRSd/fasta? [y/N] y
Successfully removed entities:
- /Users/mstolarczyk/Desktop/testing/test_genomes/rCRSd/fasta
[mstolarczyk@MichalsMBP test_genomes]: 
[mstolarczyk@MichalsMBP test_genomes]: refgenie remove -g rCRSd -a fai
refgenie 0.6.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 455, in main
    rgc.get_asset(args.genome, asset)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 212, in get_asset
    raise IOError(msg)
OSError: Asset 'fai' for genome 'rCRSd' doesn't exist; tried fasta/rCRSd.fa.fai and /Users/mstolarczyk/Desktop/testing/test_genomes/rCRSd/fasta/rCRSd.fa.fai
[mstolarczyk@MichalsMBP test_genomes]: refgenie list
refgenie 0.6.0
Local genomes: rCRSd
Local recipes: fasta, bowtie2_index, bwa_index, hisat2_index, bismark_bt2_index, bismark_bt1_index, kallisto_index, salmon_index, epilog_index, star_index, gencode_gtf, ensembl_gtf, ensembl_rb, refgene_anno, feat_annotation
Local assets:
  rCRSd: chrom_sizes, fai
```

**Comment by nsheff** [comment]
Yep, good point. I think it doesn't make sense to remove one subasset, but when you remove the primary asset you should remove all subassets.

I think this is solved by structuring assets into 'packages'

So, really, you don't install individual assets, you install asset packages. Each assset package contains one or more assets.

You also don't remove individual assets, you remove asset packages.

This just requires adding a layer into the config file to distinguish assets from packages.

**Comment by nsheff** [comment]
Do we want to piggybag this onto the config changes we're already doing for registry paths?

I'm not sure yet another layer in the config is the best solution, though... we're already adding in a layer for tags, do we need a layer underneath tags for subassets?

Maybe that is the best way forward...

```
genomes:
  hg38:   <--- genome key
  collection_checksum: 1234512341235  <--- unique genome identifier
    bowtie2_index:   <--- asset package
      1.0.0:  <--- asset tag
        bowtie2_index_local:    <--- asset key
          path: /path/to/local/asset
          asset_checksum: 123412341234    <--- unique asset identifier          
        bowtie2_index:   <--- asset key
          path:

```

**Comment by nsheff** [comment]
this brings up a question of hierarchy: are the actual asset keys (what we're calling subassets here) members of a tag, or are tags members of the subassets? I think it goes this way... tags are higher in the hierarchy than the actual subasset identifiers.

In this setting, `pull` and `remove` refer to asset packages, but `seek` refers to the asset key itself ?

**Comment by nsheff** [comment]
```
genomes:
  hg38:   <--- genome key
    genome_description: blahblahblah
    collection_checksum: 1234512341235
    asset_packages:
      bowtie2_index:   <--- asset package
        default:
          asset_checksum: 123412341234
          asset_description: blahblahblah
          path: bowtie2_index
          seek_keys:
            bowtie2_index: .
        1.0.0:  <--- asset tag
          path: /path/to/local/asset/folder
          asset_checksum: 123412341234
          asset_description: blahblahblah
      fasta:
        default:
          asset_checksum: 123412341234
          asset_description: blahblahblah
          asset_path: fasta
          seek_keys:
            fasta: hg38.fa.gz
            fai: hg38.fa.fai
            chrom_sizes: sizes.txt
        1.0.0:  <--- asset tag
          asset_checksum: 123412341234
          asset_description: blahblahblah
          asset_path: fasta
          seek_keys:
            fasta: hg38.fa.gz
            fai: hg38.fa.fai
            chrom_sizes: sizes.txt

```
